apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  annotations:
    kapp.k14s.io/versioned: ""
data:
  redis-config: |
    maxmemory 3mb
    maxmemory-policy allkeys-lru
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  annotations:
    #! Use replace strategy since Pod cannot be modified "meaningfully"
    kapp.k14s.io/update-strategy: fallback-on-replace
spec:
  containers:
  - name: redis
    image: registry.k8s.io/redis@sha256:cb111d1bd870a6a471385a4a69ad17469d326e9dd91e0e455350cacf36e1b3ee
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: 100m
    volumeMounts:
    - mountPath: /redis-data
      name: data
    - mountPath: /redis-config
      name: config
  volumes:
  - name: data
    emptyDir: {}
  - name: config
    configMap:
      name: redis-config
      items:
      - key: redis-config
        path: redis.conf
